# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('signup_expiry_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_leaving_time', models.TimeField()),
                ('driver_car_spaces', models.IntegerField()),
                ('special_requests', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
                ('is_driver', models.BooleanField()),
                ('has_own_car', models.BooleanField()),
                ('groups', models.ManyToManyField(to='backend.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='eventrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='users_attending_requests',
            field=models.ManyToManyField(to='backend.EventRequests'),
        ),
    ]
