# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 01:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRideGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_leaving', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventridegroup_requests_assigned', to='backend.User')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='date_time_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 1, 25, 39, 868496, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventridegroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Event'),
        ),
        migrations.AddField(
            model_name='eventridegroup',
            name='riders',
            field=models.ManyToManyField(related_name='eventridegroup_requests_created', to='backend.User'),
        ),
    ]
