# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequests',
            name='driver_leaving_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
