# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160816_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequests',
            name='driver_car_spaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrequests',
            name='special_requests',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
